sudo npm install gulp
sudo npm install gulp-load-plugins
sudo npm install del
sudo npm install run-sequence
sudo npm install browser-sync
sudo npm install merge-stream
sudo npm install glob
sudo npm install gulp-changed
sudo npm install gulp-autoprefixer
sudo npm install gulp-if
sudo npm install gulp-cssmin
sudo npm install gulp-size
sudo npm install gulp-cache
sudo npm install gulp-imagemin
